# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-18 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactManagerApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='id',
        ),
        migrations.AddField(
            model_name='contact',
            name='SerialNo',
            field=models.AutoField(default=b'0000000', primary_key=True, serialize=False),
        ),
    ]
