# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-18 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactManagerApp', '0002_auto_20170718_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='SerialNo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
